import cetelem from "../../assets/images/cetelem.png";
export const offers = [
  {
    id: 1,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
  {
    id: 2,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
  {
    id: 3,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
  {
    id: 4,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
  {
    id: 5,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
  {
    id: 6,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
  {
    id: 7,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
  {
    id: 8,
    name: "Сетелем",
    image: cetelem,
    price: 21507,
    percent: "6,8 % - 11,9%",
    programs: 9,
    flag: false,
  },
];
