import carImage from "../../assets/images/carq.png";
import carImage2 from "../../assets/images/car2.png";

const description = [
  "Стоимость",
  "В месяц",
  "Марка",
  "Модель",
  "Год выпуска",
  "Пробег",
  "Двигатель",
  "Коробка",
  "Привод",
  "Руль",
  "Кузов",
  "Цвет",
];

 const cars = [
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage2,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
  {
    image: carImage,
    price: "783 000 ₽",
    month: "6 000 ₽",
    brand: "Audi",
    module: "A4",
    year: "2016",
    mileage: "1",
    engine: "Бензин",
    transmission: "2.0 AMT (190 л.с) ",
    driveUnit: "Седан",
    steeringWheel: "Передний",
    body: "Робот",
    color: "Белый",
  },
];
export { description, cars };
