export const characteristics = {
  year: [],
  brand: [],
  model: [],
  newPrice: [],
  category: [],
  engine: [],
  engine_power: [],
  transmission: [],
  type_of_drive: [],
  mileage: [],
  // engine_capacity: [],
  color: [],
};
export const characteristicRequest = {
  year: null,
  brand: null,
  model: null,
  category: null,
  engine: null,
  type_of_drive: null,
  mileage: null,
  equipment: null,
  PSD: null,
  salon: null,
  KPP: null,
  modification: null,
  generation: null,
  pts_owner: null,
};
